// <auto-generated />
using System;
using HRMS_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMS_Backend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.AchievementNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ModerationLogId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModerationLogId");

                    b.HasIndex("UserId");

                    b.ToTable("AchievementNotification");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostsId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.PostImages", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("PostId");

                    b.ToTable("PostImages");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.PostInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CelebrateCount")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<int>("InsightfulCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int>("LoveCount")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("PostInteraction");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.PostModerationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModeratedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ModeratedByUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("PostModerationLog");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.PostTagMap", b =>
                {
                    b.Property<int>("PostTagMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostTagMapId"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PostTagMapId");

                    b.HasIndex("TagId");

                    b.HasIndex("PostId", "TagId")
                        .IsUnique();

                    b.ToTable("PostTagMaps");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.Posts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int?>("ModeratedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("ModeratedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.Tags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.UserPostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReactedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserPostReaction");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.FixEntityUserProfile.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavouriteSport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserBanned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId");

                    b.HasIndex("ManagerId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.BookingInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InviteReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlotId");

                    b.HasIndex("UserId");

                    b.ToTable("BookingInvite");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.BookingParticipants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("BookingsBId")
                        .HasColumnType("int");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingsBId");

                    b.HasIndex("EmpId");

                    b.HasIndex("UserId");

                    b.HasIndex("BookingId", "EmpId")
                        .IsUnique();

                    b.ToTable("BookingParticipants");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.Bookings", b =>
                {
                    b.Property<int>("BId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BId"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookedBy")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BId");

                    b.HasIndex("BookedBy");

                    b.HasIndex("SlotId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.EmployeeCycleStats", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SId"));

                    b.Property<int>("GameCycleId")
                        .HasColumnType("int");

                    b.Property<int>("GamePlayed")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SId");

                    b.HasIndex("GameCycleId");

                    b.HasIndex("UserId", "GameCycleId")
                        .IsUnique();

                    b.ToTable("EmployeeCycleStats");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.GameCycle", b =>
                {
                    b.Property<int>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CycleId"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("CycleId");

                    b.HasIndex("GamesId");

                    b.ToTable("GameCycle");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.WaitingQueue", b =>
                {
                    b.Property<int>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QueueId"));

                    b.Property<int?>("BookingsBId")
                        .HasColumnType("int");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<int?>("GameSlotsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("QueueId");

                    b.HasIndex("BookingsBId");

                    b.HasIndex("CycleId");

                    b.HasIndex("GameSlotsId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UserId");

                    b.HasIndex("SlotId", "PlayerId")
                        .IsUnique();

                    b.ToTable("WaitingQueue");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Games_Scheduling.GameConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OverTime")
                        .HasColumnType("time");

                    b.Property<int>("SlotDuration")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("GamesId")
                        .IsUnique();

                    b.ToTable("GameConfiguration");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Games_Scheduling.GameSlots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Assigned")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GameCycleCycleId")
                        .HasColumnType("int");

                    b.Property<int>("GamesId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBookingOpen")
                        .HasColumnType("bit");

                    b.Property<bool>("SlotPlayed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.HasIndex("GameCycleCycleId");

                    b.HasIndex("UserId");

                    b.HasIndex("GamesId", "StartTime")
                        .IsUnique();

                    b.ToTable("GameSlots");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Games_Scheduling.Games", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.JobListing.Jobs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ExpYearsReq")
                        .HasColumnType("int");

                    b.Property<string>("JdUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ManagedBy")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalPositions")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.JobListing.Referals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("ReffMail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReffName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReffResumeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Referals");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.JobListing.ShareEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachedFileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReceiverMail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("ShareEmail");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.ExpenseCreateEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TravelExpenseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelExpenseId");

                    b.ToTable("ExpenseCreateEmail");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.ExpensePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAmout")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExpensePolicy");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.ExpenseProof", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProofDocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelExpenseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelExpenseId");

                    b.ToTable("ExpenseProof");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.Expenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmplId")
                        .HasColumnType("int");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<string>("HrRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EmplId");

                    b.HasIndex("ExpenseType");

                    b.HasIndex("TravelId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.InAppNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InAppNotifications");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelAssignEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverMail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpId");

                    b.HasIndex("PId");

                    b.ToTable("TravelAssignEmail");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PId");

                    b.HasIndex("UserId");

                    b.HasIndex("EmpId", "PId")
                        .IsUnique();

                    b.ToTable("TravelAssignment");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelDocuments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("TravelDocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TravelPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelAssignmentId");

                    b.HasIndex("TravelPlanId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("TravelDocuments");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<string>("HrRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelAssignId")
                        .HasColumnType("int");

                    b.Property<int?>("TravelAssignmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("ExpenseType");

                    b.HasIndex("TravelAssignmentId");

                    b.ToTable("TravelExpense");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumDays")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TravelMode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("TravelPlan");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.AchievementNotification", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.Achievements.PostModerationLog", "ModerationLog")
                        .WithMany()
                        .HasForeignKey("ModerationLogId");

                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModerationLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.Comments", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", "Deleter")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId");

                    b.HasOne("HRMS_Backend.Entities.Achievements.Comments", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRMS_Backend.Entities.Achievements.Posts", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Deleter");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.PostImages", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.Achievements.Posts", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.PostInteraction", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.Achievements.Posts", "Post")
                        .WithOne("PostInteraction")
                        .HasForeignKey("HRMS_Backend.Entities.Achievements.PostInteraction", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.PostModerationLog", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Moderator");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.PostTagMap", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.Achievements.Posts", "Post")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.Achievements.Tags", "Tag")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.Posts", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "Deleter")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HRMS_Backend.Entities.User", "Moderator")
                        .WithMany("Posts")
                        .HasForeignKey("ModeratedByUserId");

                    b.HasOne("HRMS_Backend.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Deleter");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.FixEntityUserProfile.UserProfile", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("HRMS_Backend.Entities.FixEntityUserProfile.UserProfile", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.BookingInvite", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.Games_Scheduling.GameSlots", "Slot")
                        .WithMany("BookingInvite")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany("BookingInvite")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.BookingParticipants", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.GamesScheduling.Bookings", "Bookings")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.GamesScheduling.Bookings", null)
                        .WithMany("BookingParticipants")
                        .HasForeignKey("BookingsBId");

                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", null)
                        .WithMany("BookingParticipants")
                        .HasForeignKey("UserId");

                    b.Navigation("Bookings");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.Bookings", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("BookedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.Games_Scheduling.GameSlots", "GameSlots")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSlots");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.EmployeeCycleStats", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.GamesScheduling.GameCycle", "GameCycle")
                        .WithMany("EmployeeCycleStats")
                        .HasForeignKey("GameCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany("EmployeeCycleStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameCycle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.GameCycle", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.Games_Scheduling.Games", "Games")
                        .WithMany("GameCycle")
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Games");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.WaitingQueue", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.GamesScheduling.Bookings", null)
                        .WithMany("WaitingQueue")
                        .HasForeignKey("BookingsBId");

                    b.HasOne("HRMS_Backend.Entities.GamesScheduling.GameCycle", "GameCycle")
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.Games_Scheduling.GameSlots", null)
                        .WithMany("WaitingQueue")
                        .HasForeignKey("GameSlotsId");

                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.Games_Scheduling.GameSlots", "GameSlots")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", null)
                        .WithMany("WaitingQueue")
                        .HasForeignKey("UserId");

                    b.Navigation("GameCycle");

                    b.Navigation("GameSlots");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Games_Scheduling.GameConfiguration", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.Games_Scheduling.Games", "Games")
                        .WithMany("GameConfigurations")
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Games");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Games_Scheduling.GameSlots", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.GamesScheduling.GameCycle", "GameCycle")
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.GamesScheduling.GameCycle", null)
                        .WithMany("GameSlots")
                        .HasForeignKey("GameCycleCycleId");

                    b.HasOne("HRMS_Backend.Entities.Games_Scheduling.Games", "Games")
                        .WithMany("GameSlots")
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", null)
                        .WithMany("GameSlots")
                        .HasForeignKey("UserId");

                    b.Navigation("GameCycle");

                    b.Navigation("Games");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.JobListing.Jobs", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("ManagedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", null)
                        .WithMany("Jobs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.JobListing.Referals", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.JobListing.Jobs", "Job")
                        .WithMany("Referals")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", null)
                        .WithMany("Referrals")
                        .HasForeignKey("UserId");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.JobListing.ShareEmail", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.JobListing.Jobs", "Job")
                        .WithMany("ShareEmail")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", null)
                        .WithMany("ShareEmail")
                        .HasForeignKey("UserId");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.ExpenseCreateEmail", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.TravelandExpense.TravelExpense", "TravelExpense")
                        .WithMany("ExpenseCreateEmail")
                        .HasForeignKey("TravelExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelExpense");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.ExpenseProof", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.TravelandExpense.TravelExpense", "TravelExpense")
                        .WithMany()
                        .HasForeignKey("TravelExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelExpense");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.Expenses", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "HrApprover")
                        .WithMany("Expenses")
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("EmplId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.TravelandExpense.ExpensePolicy", "ExpensePolicy")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.TravelandExpense.TravelPlan", "TravelPlan")
                        .WithMany("Expenses")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpensePolicy");

                    b.Navigation("HrApprover");

                    b.Navigation("TravelPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.Notification", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany("Notification")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelAssignEmail", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany("TravelAssignEmail")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.TravelandExpense.TravelPlan", "TravelPlan")
                        .WithMany("TravelAssignEmail")
                        .HasForeignKey("PId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelAssignment", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.TravelandExpense.TravelPlan", "TravelPlan")
                        .WithMany("TravelAssignment")
                        .HasForeignKey("PId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", null)
                        .WithMany("TravelAssignment")
                        .HasForeignKey("UserId");

                    b.Navigation("TravelPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelDocuments", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.TravelandExpense.TravelAssignment", "TravelAssignment")
                        .WithMany("TravelDocuments")
                        .HasForeignKey("TravelAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.TravelandExpense.TravelPlan", null)
                        .WithMany("TravelDocuments")
                        .HasForeignKey("TravelPlanId");

                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany("TravelDocuments")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelAssignment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelExpense", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "HrApprover")
                        .WithMany("TravelExpense")
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("HRMS_Backend.Entities.TravelandExpense.ExpensePolicy", "ExpensePolicy")
                        .WithMany()
                        .HasForeignKey("ExpenseType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.TravelandExpense.TravelAssignment", null)
                        .WithMany("TravelExpense")
                        .HasForeignKey("TravelAssignmentId");

                    b.Navigation("ExpensePolicy");

                    b.Navigation("HrApprover");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelPlan", b =>
                {
                    b.HasOne("HRMS_Backend.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRMS_Backend.Entities.User", null)
                        .WithMany("TravelPlan")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.Comments", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.Posts", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostImages");

                    b.Navigation("PostInteraction")
                        .IsRequired();

                    b.Navigation("PostTagMaps");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Achievements.Tags", b =>
                {
                    b.Navigation("PostTagMaps");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.Bookings", b =>
                {
                    b.Navigation("BookingParticipants");

                    b.Navigation("WaitingQueue");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.GamesScheduling.GameCycle", b =>
                {
                    b.Navigation("EmployeeCycleStats");

                    b.Navigation("GameSlots");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Games_Scheduling.GameSlots", b =>
                {
                    b.Navigation("BookingInvite");

                    b.Navigation("Bookings");

                    b.Navigation("WaitingQueue");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.Games_Scheduling.Games", b =>
                {
                    b.Navigation("GameConfigurations");

                    b.Navigation("GameCycle");

                    b.Navigation("GameSlots");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.JobListing.Jobs", b =>
                {
                    b.Navigation("Referals");

                    b.Navigation("ShareEmail");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.ExpensePolicy", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelAssignment", b =>
                {
                    b.Navigation("TravelDocuments");

                    b.Navigation("TravelExpense");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelExpense", b =>
                {
                    b.Navigation("ExpenseCreateEmail");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.TravelandExpense.TravelPlan", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("TravelAssignEmail");

                    b.Navigation("TravelAssignment");

                    b.Navigation("TravelDocuments");
                });

            modelBuilder.Entity("HRMS_Backend.Entities.User", b =>
                {
                    b.Navigation("BookingInvite");

                    b.Navigation("BookingParticipants");

                    b.Navigation("EmployeeCycleStats");

                    b.Navigation("Expenses");

                    b.Navigation("GameSlots");

                    b.Navigation("Jobs");

                    b.Navigation("Notification");

                    b.Navigation("Posts");

                    b.Navigation("Referrals");

                    b.Navigation("ShareEmail");

                    b.Navigation("TravelAssignEmail");

                    b.Navigation("TravelAssignment");

                    b.Navigation("TravelDocuments");

                    b.Navigation("TravelExpense");

                    b.Navigation("TravelPlan");

                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("WaitingQueue");
                });
#pragma warning restore 612, 618
        }
    }
}
